spring:
  application:
    name: blood-sample-management-api
  datasource:
    username: root
    password: suhas2003
    url: jdbc:mysql://localhost:3306/bsm_bd?createDatabaseIfNotExist=true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true



