spring:
  application:
    name: blood-sample-management-api

  mail:
    host: smtp.gmail.com
    port: 587
    username: suhaskashyap2021@gmail.com
    password: qhqsaprlnlilkfdp
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true

  datasource:
    username: root
    password: suhas2003
    url: jdbc:mysql://localhost:3306/bloodemail_bd?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
